# -*- coding: utf-8 -*-
"""CodeSprintLA 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tB7Kuu0HEzZE5IIuHyuY7pKVQUkCs8p5
"""

#Problem A Majora's Math

starting_line = input().split()
starting_health = int(starting_line[0])
numbers = int(starting_line[1])

starting_line1 = input().split()
standard_damage = int(starting_line1[0])
fire_damage = int(starting_line1[1])
ice_damage = int(starting_line1[2])
light_damage = int(starting_line1[3])

for i in range(numbers):
  arr_name = input().strip()

  if arr_name == "standard":
    starting_health = starting_health - standard_damage
  elif arr_name == "fire":
    starting_health = starting_health - fire_damage
  elif arr_name == "ice":
    starting_health = starting_health - ice_damage
  elif arr_name == "light":
    starting_health = starting_health - light_damage

if starting_health <= 0:
  print("dead")
else:
  print(starting_health)

# Problem B Sneaky Lin

import sys
def SneakyLin():
  try:
    try_string = input("Enter number of test cases : ")
    if not try_string:
      return
    total = int(try_string)
  except EOFError:
    return

  for __ in range(total):
    number, K = map(int, input().split())

    levels = list(map(int, input().split()))
    total_sneakiness = 0
    negatives = []

    for s in levels:
      if s > 0:
        total_sneakiness += s
      elif s < 0:
        negatives.append(abs(s))

    negatives.sort(reverse=True)

    for f in range(len(negatives)):
      profit = negatives[f]
      penalty = (f + 1) * K

      if profit > penalty:
        total_sneakiness += profit - penalty
      else:
        break

    print(total_sneakiness)

SneakyLin()

import math

def GuardianLaser():
    try:
        line = input()
        if not line:
            return
        Total = int(line)
    except (EOFError, ValueError):
        return

    for f in range(Total):
        try:
            p, q = map(int, input().split())
        except (EOFError, ValueError):
            break

        common = math.gcd(p, q)
        p_new = p // common
        q_new = q // common

        if p_new % 2 == 0:
            print("B")
        elif q_new % 2 == 0:
            print("A")
        else:

            if p % 2 == 1:
                print("A")
            else:
                print("B")

if __name__ == "__main__":
    GuardianLaser()

# Problem H Rune Decryption

import sys
from collections import deque

def check_stability_condition(threshold_level, energy_grid, grid_size, min_active_required):
    active_count = 0
    starting_point = None

    is_active_map = [[False] * grid_size for _ in range(grid_size)]

    for row_idx in range(grid_size):
        for col_idx in range(grid_size):
            if energy_grid[row_idx][col_idx] >= threshold_level:
                active_count += 1
                is_active_map[row_idx][col_idx] = True
                if starting_point is None:
                    starting_point = (row_idx, col_idx)

    if active_count < min_active_required:
        return False

    if not starting_point:
        return False

    connected_points_found = 0
    traversal_queue = deque([starting_point])
    visited_tiles = [[False] * grid_size for _ in range(grid_size)]
    visited_tiles[starting_point[0]][starting_point[1]] = True

    while traversal_queue:
        current_row, current_col = traversal_queue.popleft()
        connected_points_found += 1


        for delta_row, delta_col in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            neighbor_row = current_row + delta_row
            neighbor_col = current_col + delta_col


            if 0 <= neighbor_row < grid_size and 0 <= neighbor_col < grid_size:
                if is_active_map[neighbor_row][neighbor_col] and not visited_tiles[neighbor_row][neighbor_col]:
                    visited_tiles[neighbor_row][neighbor_col] = True
                    traversal_queue.append((neighbor_row, neighbor_col))


    return connected_points_found == active_count

def solve_rune_decryption():
    try:
        input_data = input().strip()
        if not input_data:
            return
        grid_size = int(input_data)
    except EOFError:
        return

    energy_grid = []
    unique_energy_values = set()

    for _ in range(grid_size):
        current_row_data = list(map(int, input().split()))
        energy_grid.append(current_row_data)
        for energy_value in current_row_data:
            unique_energy_values.add(energy_value)


    sorted_unique_values = sorted(list(unique_energy_values))

    lower_bound = 0
    upper_bound = len(sorted_unique_values) - 1
    best_focus_level = sorted_unique_values[0]


    while lower_bound <= upper_bound:
        middle_index = (lower_bound + upper_bound) // 2
        current_test_level = sorted_unique_values[middle_index]


        if check_stability_condition(current_test_level, energy_grid, grid_size, grid_size):
            best_focus_level = current_test_level
            lower_bound = middle_index + 1
        else:
            upper_bound = middle_index - 1

    print(best_focus_level)

if __name__ == "__main__":
    solve_rune_decryption()

