# -*- coding: utf-8 -*-
"""Problem H Rune Decryption.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhPX6ISDovhBV9Ei7d1VeyLh45oulgpL
"""

# Problem H Rune Decryption

import sys
from collections import deque

def check_stability_condition(threshold_level, energy_grid, grid_size, min_active_required):
    active_count = 0
    starting_point = None

    is_active_map = [[False] * grid_size for _ in range(grid_size)]

    for row_idx in range(grid_size):
        for col_idx in range(grid_size):
            if energy_grid[row_idx][col_idx] >= threshold_level:
                active_count += 1
                is_active_map[row_idx][col_idx] = True
                if starting_point is None:
                    starting_point = (row_idx, col_idx)

    if active_count < min_active_required:
        return False

    if not starting_point:
        return False

    connected_points_found = 0
    traversal_queue = deque([starting_point])
    visited_tiles = [[False] * grid_size for _ in range(grid_size)]
    visited_tiles[starting_point[0]][starting_point[1]] = True

    while traversal_queue:
        current_row, current_col = traversal_queue.popleft()
        connected_points_found += 1


        for delta_row, delta_col in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            neighbor_row = current_row + delta_row
            neighbor_col = current_col + delta_col


            if 0 <= neighbor_row < grid_size and 0 <= neighbor_col < grid_size:
                if is_active_map[neighbor_row][neighbor_col] and not visited_tiles[neighbor_row][neighbor_col]:
                    visited_tiles[neighbor_row][neighbor_col] = True
                    traversal_queue.append((neighbor_row, neighbor_col))


    return connected_points_found == active_count

def solve_rune_decryption():
    try:
        input_data = input().strip()
        if not input_data:
            return
        grid_size = int(input_data)
    except EOFError:
        return

    energy_grid = []
    unique_energy_values = set()

    for _ in range(grid_size):
        current_row_data = list(map(int, input().split()))
        energy_grid.append(current_row_data)
        for energy_value in current_row_data:
            unique_energy_values.add(energy_value)


    sorted_unique_values = sorted(list(unique_energy_values))

    lower_bound = 0
    upper_bound = len(sorted_unique_values) - 1
    best_focus_level = sorted_unique_values[0]


    while lower_bound <= upper_bound:
        middle_index = (lower_bound + upper_bound) // 2
        current_test_level = sorted_unique_values[middle_index]


        if check_stability_condition(current_test_level, energy_grid, grid_size, grid_size):
            best_focus_level = current_test_level
            lower_bound = middle_index + 1
        else:
            upper_bound = middle_index - 1

    print(best_focus_level)

if __name__ == "__main__":
    solve_rune_decryption()